Config = Config or {}

--[[
    Data-driven production recipes.
    requiredItems / rewards use itemName = amount maps.
    Optional fields: duration, animation, scenario, skillCheck, temperatureGame,
    dispatchChance, requireMask, packagingOptions, plantAction, metadataFromInput
]]

Config.Recipes = {
    cocaine = {
        {
            id = 'unpack',
            label = 'Unpack powdered milk',
            station = 'unpack',
            duration = 12000,
            animation = { dict = 'anim@amb@business@coc@coc_unpack_cut@', clip = 'fullcut_cycle_v1_cokepacker' },
            skillCheck = { 'easy', 'easy' },
            requiredItems = { powdered_milk = 1 },
            rewards = { coke_pile = 3 },
            dispatchChance = 5,
            baseQuality = 55,
        },
        {
            id = 'cut',
            label = 'Cut cocaine',
            station = 'cut',
            duration = 15000,
            animation = { dict = 'anim@amb@business@coc@coc_unpack_cut_left@', clip = 'coke_cut_coccutter' },
            skillCheck = { 'easy', 'medium' },
            requiredItems = { coke_pile = 1 },
            rewards = { cut_coke = 2 },
            dispatchChance = 8,
            qualityBonusOnSuccess = 8,
            qualityPenaltyOnFail = 15,
            metadataFromInput = true,
        },
        {
            id = 'pack_1g',
            label = 'Package 1g bag',
            station = 'packing',
            duration = 8000,
            animation = { dict = 'mp_arresting', clip = 'a_uncuff' },
            requiredItems = { cut_coke = 1, empty_bag = 1 },
            rewards = { coke_1g = 1 },
            packaging = '1g',
            metadataFromInput = true,
            createBatch = true,
        },
        {
            id = 'pack_5g',
            label = 'Package 5g bag',
            station = 'packing',
            duration = 10000,
            animation = { dict = 'mp_arresting', clip = 'a_uncuff' },
            requiredItems = { cut_coke = 5, empty_bag = 1 },
            rewards = { coke_5g = 1 },
            packaging = '5g',
            metadataFromInput = true,
            createBatch = true,
        },
        {
            id = 'pack_10g',
            label = 'Package 10g bag',
            station = 'packing',
            duration = 12000,
            animation = { dict = 'mp_arresting', clip = 'a_uncuff' },
            requiredItems = { cut_coke = 10, empty_bag = 1 },
            rewards = { coke_10g = 1 },
            packaging = '10g',
            metadataFromInput = true,
            createBatch = true,
        },
    },

    meth = {
        {
            id = 'mix',
            label = 'Mix chemicals',
            station = 'mix',
            duration = 16000,
            animation = { dict = 'anim@amb@business@meth@meth_monitoring_no_work@', clip = 'cleaning_pour_no_work_lazycook' },
            skillCheck = { 'easy', 'medium' },
            requireMask = true,
            requiredItems = {
                ammonia = 1,
                sulfuric_acid = 1,
                hydrochloric_acid = 1,
            },
            rewards = { meth_mixture = 1 },
            dispatchChance = 10,
            baseQuality = 60,
            qualityBonusOnSuccess = 10,
        },
        {
            id = 'furnace',
            label = 'Heat mixture',
            station = 'furnace',
            duration = 20000,
            animation = { dict = 'anim@amb@business@meth@meth_monitoring_cooking@cooking@', clip = 'chemical_pour_long_cooker' },
            requireMask = true,
            temperatureGame = true,
            requiredItems = { meth_mixture = 1 },
            rewards = { meth_mixture = 1 },
            metadataFromInput = true,
            transformSameItem = true,
            dispatchChance = 15,
            failDispatchChance = 65,
        },
        {
            id = 'chemical_mixer',
            label = 'Chemical mixer',
            station = 'chemical_mixer',
            duration = 18000,
            animation = { dict = 'anim@amb@business@meth@meth_monitoring_no_work@', clip = 'cleaning_pour_no_work_lazycook' },
            skillCheck = { 'medium', 'medium' },
            requireMask = true,
            requiredItems = {
                meth_mixture = 1,
                lithium = 1,
                phosphorus = 1,
            },
            rewards = { meth_beaker = 1 },
            metadataFromInput = true,
            dispatchChance = 12,
            qualityBonusOnSuccess = 5,
        },
        {
            id = 'tray',
            label = 'Pour on tray',
            station = 'tray',
            duration = 10000,
            animation = { dict = 'weapon@w_sp_jerrycan', clip = 'fire' },
            requiredItems = { meth_beaker = 1, empty_tray = 1 },
            rewards = { meth_tray = 1 },
            metadataFromInput = true,
        },
        {
            id = 'break',
            label = 'Break crystals',
            station = 'break_crystal',
            duration = 12000,
            animation = { dict = 'amb@world_human_hammering@male@base', clip = 'base' },
            skillCheck = { 'easy', 'medium' },
            requiredItems = { meth_tray = 1 },
            rewards = { meth_crystal = 4, empty_tray = 1 },
            metadataFromInput = true,
            createBatch = false,
        },
        {
            id = 'pack_1g',
            label = 'Package 1g meth',
            station = 'packing',
            duration = 8000,
            animation = { dict = 'mp_arresting', clip = 'a_uncuff' },
            requiredItems = { meth_crystal = 1, empty_bag = 1 },
            rewards = { meth_1g = 1 },
            packaging = '1g',
            metadataFromInput = true,
            createBatch = true,
        },
        {
            id = 'pack_5g',
            label = 'Package 5g meth',
            station = 'packing',
            duration = 10000,
            animation = { dict = 'mp_arresting', clip = 'a_uncuff' },
            requiredItems = { meth_crystal = 5, empty_bag = 1 },
            rewards = { meth_5g = 1 },
            packaging = '5g',
            metadataFromInput = true,
            createBatch = true,
        },
        {
            id = 'pack_10g',
            label = 'Package 10g meth',
            station = 'packing',
            duration = 12000,
            animation = { dict = 'mp_arresting', clip = 'a_uncuff' },
            requiredItems = { meth_crystal = 10, empty_bag = 1 },
            rewards = { meth_10g = 1 },
            packaging = '10g',
            metadataFromInput = true,
            createBatch = true,
        },
    },

    acid = {
        {
            id = 'bottling',
            label = 'Bottle acid',
            station = 'bottling',
            duration = 10000,
            animation = { dict = 'anim@amb@business@meth@meth_monitoring_no_work@', clip = 'cleaning_pour_no_work_lazycook' },
            skillCheck = { 'easy' },
            requiredItems = { empty_bottle = 1, acid_mix = 1 },
            rewards = { acid_bottle = 1 },
            baseQuality = 70,
            dispatchChance = 8,
        },
        {
            id = 'packing',
            label = 'Package acid',
            station = 'packing',
            duration = 9000,
            animation = { dict = 'mp_arresting', clip = 'a_uncuff' },
            requiredItems = { acid_bottle = 1, packaging = 1 },
            rewards = { acid_package = 1 },
            metadataFromInput = true,
            createBatch = true,
        },
    },

    weed = {
        {
            id = 'plant',
            label = 'Plant seed',
            station = 'plant',
            plantAction = 'plant',
            duration = 8000,
            animation = { dict = 'amb@world_human_gardener_plant@male@base', clip = 'base' },
            requiredItems = { weed_seed = 1 },
            rewards = {},
        },
        {
            id = 'water',
            label = 'Water plant',
            station = 'plant',
            plantAction = 'water',
            duration = 5000,
            animation = { dict = 'weapon@w_sp_jerrycan', clip = 'fire' },
            requiredItems = { plant_water = 1 },
            rewards = {},
        },
        {
            id = 'nutrients',
            label = 'Add nutrients',
            station = 'plant',
            plantAction = 'nutrients',
            duration = 5000,
            animation = { dict = 'weapon@w_sp_jerrycan', clip = 'fire' },
            requiredItems = { plant_nutrient = 1 },
            rewards = {},
        },
        {
            id = 'spray',
            label = 'Spray plant',
            station = 'plant',
            plantAction = 'spray',
            duration = 4000,
            animation = { dict = 'timetable@gardener@lawnmow@', clip = 'base' },
            requiredItems = { plant_spray = 1 },
            rewards = {},
        },
        {
            id = 'harvest',
            label = 'Harvest plant',
            station = 'plant',
            plantAction = 'harvest',
            duration = 10000,
            animation = { dict = 'amb@world_human_gardener_plant@male@base', clip = 'base' },
            requiredItems = {},
            rewards = { weed_bud = 1 },
            createBatch = true,
        },
        {
            id = 'pack_1g',
            label = 'Package 1g weed',
            station = 'packing',
            duration = 7000,
            animation = { dict = 'mp_arresting', clip = 'a_uncuff' },
            requiredItems = { weed_bud = 1, empty_bag = 1 },
            rewards = { weed_1g = 1 },
            packaging = '1g',
            metadataFromInput = true,
            createBatch = true,
        },
        {
            id = 'pack_5g',
            label = 'Package 5g weed',
            station = 'packing',
            duration = 9000,
            animation = { dict = 'mp_arresting', clip = 'a_uncuff' },
            requiredItems = { weed_bud = 5, empty_bag = 1 },
            rewards = { weed_5g = 1 },
            packaging = '5g',
            metadataFromInput = true,
            createBatch = true,
        },
        {
            id = 'pack_10g',
            label = 'Package 10g weed',
            station = 'packing',
            duration = 11000,
            animation = { dict = 'mp_arresting', clip = 'a_uncuff' },
            requiredItems = { weed_bud = 10, empty_bag = 1 },
            rewards = { weed_10g = 1 },
            packaging = '10g',
            metadataFromInput = true,
            createBatch = true,
        },
    },

    empty = {},
    mdma = {},
    heroin = {},
    lsd = {},
    crack = {},
    fentanyl = {},
}
