Products = {
    -- Horny's Burgers
    hornys_burger_classic = {
        id = 'hornys_burger_classic',
        label = 'Burger Classic',
        description = 'Burger classique Horny\'s.',
        price = 650,
        category = 'Burgers',
        color = '#E74C3C',
        item = 'hornys_burger_classic',
        recipe = 'hornys_burger_classic',
        prepTime = 10000,
        restaurants = { hornys = true },
        available = true,
        sellable = true,
    },
    hornys_burger_bone = {
        id = 'hornys_burger_bone',
        label = 'Burger The Beef with the Bone',
        description = 'Signature Horny\'s — viande premium.',
        price = 850,
        category = 'Burgers',
        color = '#C0392B',
        item = 'hornys_burger_bone',
        recipe = 'hornys_burger_bone',
        prepTime = 12000,
        restaurants = { hornys = true },
        available = true,
        sellable = true,
    },
    hornys_fries = {
        id = 'hornys_fries',
        label = 'Frites Horny\'s',
        description = 'Frites croustillantes.',
        price = 350,
        category = 'Accompagnements',
        color = '#F39C12',
        item = 'hornys_fries',
        recipe = 'hornys_fries',
        prepTime = 7000,
        restaurants = { hornys = true },
        available = true,
        sellable = true,
    },
    hornys_nuggets = {
        id = 'hornys_nuggets',
        label = 'Nuggets',
        description = '6 pièces de nuggets croustillants.',
        price = 450,
        category = 'Accompagnements',
        color = '#D35400',
        item = 'hornys_nuggets',
        recipe = 'hornys_nuggets',
        prepTime = 9000,
        restaurants = { hornys = true },
        available = true,
        sellable = true,
    },
    hornys_tacos = {
        id = 'hornys_tacos',
        label = 'Tacos Horny\'s',
        description = 'Tacos maison épicés.',
        price = 550,
        category = 'Burgers',
        color = '#E67E22',
        item = 'hornys_tacos',
        recipe = 'hornys_tacos',
        prepTime = 10000,
        restaurants = { hornys = true },
        available = true,
        sellable = true,
    },
    hornys_milkshake = {
        id = 'hornys_milkshake',
        label = 'Milkshake',
        description = 'Milkshake onctueux.',
        price = 400,
        category = 'Boissons',
        color = '#8E44AD',
        item = 'hornys_milkshake',
        recipe = 'hornys_milkshake',
        prepTime = 5000,
        restaurants = { hornys = true },
        available = true,
        sellable = true,
    },
    hornys_cola = {
        id = 'hornys_cola',
        label = 'Cola',
        description = 'Boisson fraîche.',
        price = 300,
        category = 'Boissons',
        color = '#5D6D7E',
        item = 'hornys_cola',
        recipe = 'hornys_cola',
        prepTime = 4000,
        restaurants = { hornys = true },
        available = true,
        sellable = true,
    },
    hornys_menu_combo = {
        id = 'hornys_menu_combo',
        label = 'Menu Combo Horny\'s',
        description = 'Burger signature, frites et boisson.',
        price = 1200,
        category = 'Menus',
        color = '#A93226',
        item = 'hornys_menu_combo',
        recipe = 'hornys_menu_combo',
        prepTime = 15000,
        restaurants = { hornys = true },
        available = true,
        sellable = true,
    },

    -- Greasy Joe's Diner
    greasy_breakfast = {
        id = 'greasy_breakfast',
        label = 'Petit-déjeuner complet',
        description = 'Œufs, bacon, toast et pommes de terre.',
        price = 900,
        category = 'Petit-déjeuner',
        color = '#2980B9',
        item = 'greasy_breakfast',
        recipe = 'greasy_breakfast',
        prepTime = 14000,
        restaurants = { greasy_joes = true },
        available = true,
        sellable = true,
    },
    greasy_pancakes = {
        id = 'greasy_pancakes',
        label = 'Pancakes',
        description = 'Stack de pancakes au sirop.',
        price = 600,
        category = 'Petit-déjeuner',
        color = '#F1C40F',
        item = 'greasy_pancakes',
        recipe = 'greasy_pancakes',
        prepTime = 10000,
        restaurants = { greasy_joes = true },
        available = true,
        sellable = true,
    },
    greasy_bacon_eggs = {
        id = 'greasy_bacon_eggs',
        label = 'Bacon & Œufs',
        description = 'Œufs au plat et bacon croustillant.',
        price = 750,
        category = 'Petit-déjeuner',
        color = '#E67E22',
        item = 'greasy_bacon_eggs',
        recipe = 'greasy_bacon_eggs',
        prepTime = 11000,
        restaurants = { greasy_joes = true },
        available = true,
        sellable = true,
    },
    greasy_burger = {
        id = 'greasy_burger',
        label = 'Burger Diner',
        description = 'Burger maison style diner américain.',
        price = 700,
        category = 'Plats',
        color = '#D35400',
        item = 'greasy_burger',
        recipe = 'greasy_burger',
        prepTime = 11000,
        restaurants = { greasy_joes = true },
        available = true,
        sellable = true,
    },
    greasy_fries = {
        id = 'greasy_fries',
        label = 'Frites maison',
        description = 'Frites épaisses croustillantes.',
        price = 350,
        category = 'Accompagnements',
        color = '#F39C12',
        item = 'greasy_fries',
        recipe = 'greasy_fries',
        prepTime = 7000,
        restaurants = { greasy_joes = true },
        available = true,
        sellable = true,
    },
    greasy_coffee = {
        id = 'greasy_coffee',
        label = 'Café',
        description = 'Café chaud infusé.',
        price = 250,
        category = 'Boissons',
        color = '#6E2C00',
        item = 'greasy_coffee',
        recipe = 'greasy_coffee',
        prepTime = 5000,
        restaurants = { greasy_joes = true },
        available = true,
        sellable = true,
    },
    greasy_orange_juice = {
        id = 'greasy_orange_juice',
        label = 'Jus d\'orange',
        description = 'Jus pressé frais.',
        price = 350,
        category = 'Boissons',
        color = '#E67E22',
        item = 'greasy_orange_juice',
        recipe = 'greasy_orange_juice',
        prepTime = 4000,
        restaurants = { greasy_joes = true },
        available = true,
        sellable = true,
    },
    greasy_milkshake = {
        id = 'greasy_milkshake',
        label = 'Milkshake Diner',
        description = 'Milkshake onctueux style 50\'s.',
        price = 450,
        category = 'Boissons',
        color = '#8E44AD',
        item = 'greasy_milkshake',
        recipe = 'greasy_milkshake',
        prepTime = 5000,
        restaurants = { greasy_joes = true },
        available = true,
        sellable = true,
    },
}

Config.Products = Products

---@param id string
---@return table|nil
function Rest.GetProduct(id)
    return Products[id]
end

---@param restaurantKey string|nil
---@return table[]
function Rest.GetSellableProducts(restaurantKey)
    local list = {}
    for id, product in pairs(Products) do
        if product.sellable ~= false and product.available ~= false then
            if not restaurantKey or not product.restaurants or product.restaurants[restaurantKey] then
                list[#list + 1] = {
                    id = id,
                    label = product.label,
                    description = product.description,
                    price = product.price,
                    category = product.category,
                    color = product.color,
                    prepTime = product.prepTime,
                }
            end
        end
    end
    table.sort(list, function(a, b) return a.label < b.label end)
    return list
end
